// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'


export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server<{
  supabase: any;
  userId: string;
  claims: any;
}>(
  async ({ next }) => {
    
    try {
      // Try to get credentials
      let SUPABASE_URL: string | undefined;
      let SUPABASE_PUBLISHABLE_KEY: string | undefined;

      try {
        if (typeof process !== 'undefined' && process.env) {
          SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
          SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;
        }
      } catch (e) {}

      const isValid = SUPABASE_URL &&
        SUPABASE_PUBLISHABLE_KEY && 
        SUPABASE_URL !== 'https://placeholder.supabase.co' && 
        SUPABASE_URL.startsWith('http');

      if (!isValid) {
        // Demo mode: no auth required!
        console.warn('[Supabase Auth] Demo mode - no real authentication');
        return next({
          context: {
            supabase: {
              from: () => ({
                select: () => ({
                  data: [],
                  error: null,
                  eq: () => ({ data: [], error: null }),
                  neq: () => ({ data: [], error: null }),
                  limit: () => ({ data: [], error: null }),
                  order: () => ({ data: [], error: null }),
                }),
                insert: () => ({ data: [], error: null }),
                update: () => ({ data: [], error: null }),
                delete: () => ({ data: [], error: null }),
              }),
            },
            userId: 'demo-user-id-1234',
            claims: { sub: 'demo-user-id-1234' }
          }
        });
      }

      // Try real auth
      const { getRequest } = await import('@tanstack/react-start/server');
      const request = getRequest();
      const authHeader = request?.headers?.get('authorization');

      if (!authHeader || !authHeader.startsWith('Bearer ')) {
        throw new Error('Unauthorized');
      }

      const token = authHeader.slice(7);
      const supabase = createClient<Database>(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
        {
          global: { headers: { Authorization: `Bearer ${token}` } },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims || !data.claims.sub) {
        throw new Error('Unauthorized');
      }

      return next({
        context: {
          supabase: supabase as any,
          userId: data.claims.sub,
          claims: data.claims
        }
      });
    } catch (e) {
      console.warn('[Supabase Auth] Demo mode fallback');
      return next({
        context: {
          supabase: {
            from: () => ({
              select: () => ({
                data: [],
                error: null,
                eq: () => ({ data: [], error: null }),
                neq: () => ({ data: [], error: null }),
                limit: () => ({ data: [], error: null }),
                order: () => ({ data: [], error: null }),
              }),
              insert: () => ({ data: [], error: null }),
              update: () => ({ data: [], error: null }),
              delete: () => ({ data: [], error: null }),
            }),
          },
          userId: 'demo-user-id-1234',
          claims: { sub: 'demo-user-id-1234' }
        }
      });
    }
  }
);
