// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
// import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fully mocked client that does absolutely nothing
const getMockClient = (): any => {
  return {
    from: () => ({
      select: () => ({
        data: [],
        error: null,
        eq: () => ({ data: [], error: null }),
        neq: () => ({ data: [], error: null }),
        limit: () => ({ data: [], error: null }),
        order: () => ({ data: [], error: null }),
        maybeSingle: () => ({ data: null, error: null }),
        single: () => ({ data: null, error: null }),
      }),
      insert: () => ({ data: [], error: null }),
      update: () => ({ data: [], error: null }),
      delete: () => ({ data: [], error: null }),
    }),
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
    }
  };
};

function createSupabaseAdminClient() {
  try {
    let SUPABASE_URL: string | undefined;
    let SUPABASE_SERVICE_ROLE_KEY: string | undefined;

    try {
      if (typeof process !== 'undefined' && process.env) {
        SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
        SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
      }
    } catch (e) {}

    const isValid = SUPABASE_URL &&
      SUPABASE_SERVICE_ROLE_KEY && 
      SUPABASE_URL !== 'https://placeholder.supabase.co' && 
      SUPABASE_URL.startsWith('http');

    if (!isValid) {
      console.warn('[Supabase Admin] No valid credentials found, using mock client');
      return getMockClient();
    }

    console.log('[Supabase Admin] Initializing with valid credentials');
    const { createClient } = require('@supabase/supabase-js');
    return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      }
    });
  } catch (e) {
    console.warn('[Supabase Admin] Error initializing admin client, using mock:', e);
    return getMockClient();
  }
}

let _supabaseAdmin: any | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as any, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
