// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 
    (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined) ||
    (typeof process !== 'undefined' ? process.env.VITE_SUPABASE_URL : undefined);
    
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
    (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined) ||
    (typeof process !== 'undefined' ? process.env.VITE_SUPABASE_PUBLISHABLE_KEY : undefined);

  console.log('[Supabase Client] Initializing with URL:', SUPABASE_URL ? 'PRESENT' : 'MISSING');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_URL === 'undefined' || SUPABASE_PUBLISHABLE_KEY === 'undefined') {
    const missing = [
      ...(!SUPABASE_URL || SUPABASE_URL === 'undefined' ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'undefined' ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please check your .env file and ensure VITE_ prefix is used.`;
    console.error(`[Supabase] ${message}`);
    
    if (typeof window !== 'undefined') {
       console.log('[Supabase Debug] import.meta.env keys:', Object.keys(import.meta.env));
       console.log('[Supabase Debug] VITE_SUPABASE_URL value:', import.meta.env.VITE_SUPABASE_URL);
    }
    
    // Fallback to a dummy URL to prevent the "Invalid supabaseUrl" crash from @supabase/supabase-js
    // This allows the UI to at least render so the user can see the error toast/message.
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder-key');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
