// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fully mocked client that does absolutely nothing
const getMockClient = (): any => {
  return {
    from: () => ({
      select: () => ({
        data: [],
        error: null,
        eq: () => ({ data: [], error: null }),
        neq: () => ({ data: [], error: null }),
        limit: () => ({ data: [], error: null }),
        order: () => ({ data: [], error: null }),
        maybeSingle: () => ({ data: null, error: null }),
        single: () => ({ data: null, error: null }),
        then: (fn: any) => fn({ data: [], error: null })
      }),
      insert: () => ({ data: [], error: null, then: (fn: any) => fn({ data: [], error: null }) }),
      update: () => ({ data: [], error: null, then: (fn: any) => fn({ data: [], error: null }) }),
      delete: () => ({ data: [], error: null, then: (fn: any) => fn({ data: [], error: null }) }),
    }),
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => {} } },
        error: null
      }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: null }),
      signInWithOAuth: async () => ({ data: null, error: null }),
      signUp: async () => ({ data: { user: null, session: null }, error: null }),
      signOut: async () => ({ error: null }),
      setSession: async () => {},
    }
  };
};

function createSupabaseClient() {
  try {
    // Try to get credentials
    let SUPABASE_URL: string | undefined;
    let SUPABASE_PUBLISHABLE_KEY: string | undefined;

    if (typeof import.meta !== 'undefined' && import.meta.env) {
      SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
      SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
    }

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      try {
        if (typeof process !== 'undefined' && process.env) {
          SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
          SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
        }
      } catch (e) { }
    }

    // Validate credentials
    const isValid = SUPABASE_URL && 
      SUPABASE_PUBLISHABLE_KEY && 
      SUPABASE_URL !== 'https://placeholder.supabase.co' && 
      SUPABASE_URL !== 'undefined' && 
      SUPABASE_URL.startsWith('http');

    if (!isValid) {
      console.warn('[Supabase] No valid Supabase credentials found, using mock client');
      return getMockClient();
    }

    // If valid, try to create the real client
    console.log('[Supabase] Initializing with valid client');
    const { createClient } = require('@supabase/supabase-js');
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      }
    });
  } catch (e) {
    console.warn('[Supabase] Error initializing client, using mock client instead:', e);
    return getMockClient();
  }
}

let _supabase: any | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as any, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
